spring.application.name=backend
server.port=${PORT:8080}

# CONEXIÓN SQL POSTGRESQL LOCAL
spring.datasource.url=jdbc:postgresql://localhost:5432/restaiuranteboard_sql
spring.datasource.username=postgres
spring.datasource.password=db_743W4R743W!
spring.datasource.driver-class-name=org.postgresql.Driver

# CONEXIÓN NOSQL MONGODB LOCAL
spring.data.mongodb.uri=mongodb://user_db:aba76PXAWzfL634w@localhost:27017/restaiuranteboard_nosql?authSource=admin
spring.data.mongodb.database=restaiuranteboard_nosql

# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
